# Step 1: Build the React app
FROM node:20-alpine AS build

WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm install

COPY . ./
RUN npm run build

# Step 2: Serve with Nginx
FROM nginx:stable-alpine

# Copy the built React app from the build stage
COPY --from=build /app/build /usr/share/nginx/html

# Add this line to use the custom config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
