spring.application.name=order-service
server.port=8081
spring.data.mongodb.uri=mongodb+srv://Pasan:Pasan%402003@ordermanagement.h6iv1p5.mongodb.net/orderDetails



spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_menu
spring.datasource.username=postgres
spring.datasource.password=admin1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
