spring.application.name=order-service
server.port=8081
spring.data.mongodb.uri=mongodb+srv://Pasan:Pasan%402003@ordermanagement.h6iv1p5.mongodb.net/orderDetails


# Disable SQL datasource auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration