spring.application.name=delivery_service
server.port=8081


spring.data.mongodb.uri=mongodb+srv://malmi:Malmi%40123@cluster0.55k6k1s.mongodb.net/delivery_service



# Disable default SQL DataSource auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration