spring.application.name=delivery_service
server.port=8081

spring.data.mongodb.uri=mongodb+srv://malmi:Malmi%40123@cluster0.55k6k1s.mongodb.net/delivery_service


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

google.maps.api.key=AIzaSyBAAu_9NQjq6m33d7_STIOiOHfC6ZuaEqg

# RestTemplate timeout settings
rest.template.connection.timeout=5000
rest.template.read.timeout=5000

# Disable default SQL DataSource auto-configuration
#spring.autoconfigure.exclude=ogit checkout origin/dev_Pasan -- backend/services/order-servicerg.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration